name: ci
on:
  push:
  pull_request:
  schedule:
  - cron: '0 2 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
            scala: 2_11
          - java: 8
            scala: 2_12
          - java: 8
            scala: 2_13
          - java: 8
            scala: 3
          - java: 11
            scala: 2
    steps:
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.${{matrix.java}}"
    - uses: actions/checkout@v2.3.4
    - uses: coursier/cache-action@v6
    - run: |
        export TZ=Australia/Canberra
        case ${{ matrix.scala }} in
          2_11)
            sbt -v scalafmtSbtCheck SetScala211 scalafmtCheckAll test
            ;;
          2_12)
            sbt -v scalafmtSbtCheck SetScala212 scalafmtCheckAll test
            ;;
          2_13)
            sbt -v scalafmtSbtCheck SetScala213 scalafmtCheckAll test
            ;;
          2)
            sbt -v scalafmtSbtCheck scalafmtCheckAll test
            ;;
          3)
            sbt -v \
            scalafmtSbtCheck \
            '++ 3.0.0-RC1!' \
            scalafmtCheckAll \
            "all json4s-astJVM/test json4s-scalap/test" \
            '++ 3.0.0-RC2!' \
            "all json4s-astJS/compile json4s-astJVM/compile json4s-jackson-core/compile json4s-native-coreJS/compile json4s-native-coreJVM/compile json4s-scalap/compile json4s-scalazJS/compile json4s-scalazJVM/compile json4s-xmlJS/compile json4s-xmlJVM/compile"
            ;;
          *)
            echo "unknown scala version"
            exit 1
        esac
